# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YSLiveSample' do
  
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'AFNetworking', '~> 3.2.1'
  pod 'SDWebImage', '~> 5.3.2'
  pod 'Masonry', '~> 1.1.0'
  pod 'TZImagePickerController', '~> 3.2.7'
  pod 'FMDB', '~> 2.7.5'
  pod 'SSZipArchive', '~> 2.2.2'

end
